version: "3"
services:
  de-ondics-minio:
    build: ./
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=scaleit
      - MINIO_ROOT_PASSWORD=scaleitscaleit
    #volumes:
    #  - de-ondics-minio:/data
    command: server /data --console-address ":9001"